name       : xdg-dbus-proxy
version    : 0.1.4
release    : 4
source     :
    - https://github.com/flatpak/xdg-dbus-proxy/releases/download/0.1.4/xdg-dbus-proxy-0.1.4.tar.xz : 1ec0eab53d1e49966d722352bcfd51ac402dce5190baedc749a8541e761670ab
license    : LGPL-2.1-or-later
component  : security
summary    : Filtering proxy for D-Bus connections.
description: |
    xdg-dbus-proxy is a filtering proxy for D-Bus connections. It was originally part of the flatpak project, but it has been broken out as a standalone module to facilitate using it in other contexts.
builddeps  :
    - docbook-xml
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
