name       : xdg-dbus-proxy
version    : 0.1.2
release    : 1
source     :
    - https://github.com/flatpak/xdg-dbus-proxy/releases/download/0.1.2/xdg-dbus-proxy-0.1.2.tar.xz : 1749d6f9f46dcc9edc87725641cf56cf91dcad1b01707891ea0850c1000c520f
license    : LGPL-2.1-or-later
component  : security
summary    : Filtering proxy for D-Bus connections.
description: |
    xdg-dbus-proxy is a filtering proxy for D-Bus connections. It was originally part of the flatpak project, but it has been broken out as a standalone module to facilitate using it in other contexts.
builddeps  :
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
